# Generated by Django 5.2.4 on 2025-07-15 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('complaint_type', models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('billing', 'Billing'), ('other', 'Other')], default='general', max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('REJECT', 'Reject'), ('IN_PROGRESS', 'In Progress')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_status_by', models.CharField(blank=True, max_length=100, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
