# Generated by Django 4.2.23 on 2025-07-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.BigIntegerField()),
                ('description', models.TextField()),
                ('complaint_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('update_status_by', models.CharField(blank=True, max_length=100, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
