# Generated by Django 5.2.4 on 2025-07-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_alter_complaint_complaint_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
