# Generated by Django 5.2.4 on 2025-07-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0003_alter_complaint_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
